### PR TITLE
Support FEEL expression in Script Task

### LINKED ISSUE #38: Support `implementation` rule in bpmnlint-plugin-camunda-compat
So that `zeebe:Script` is properly linted.

### PR DESCRIPTION
**Pull request by barmac**
Closes #38

### CODE REVIEW

**Comment by barmac** [comment]
Fixed.

**Review by nikku — CHANGES_REQUESTED** [review]
Works as intended for 8.2.

Does not validate constraints for 8.1, why is that (cf. screenshot below). Is there a reason for this interaction?

As a user I'd expect the structural integrity of the FEEL binding (if provided) to still be validated.
capture YT6FKJ_optimized

**Comment by nikku** [comment]
I'd expect `FEEL expression` to validate in either case.

**Comment by barmac** [comment]
Hmm that's against the existing convention:
image

**Comment by barmac** [comment]
Also note that such validation does not protect the user against deployment error. Also they get 3 errors of which only 1 is important -> property is not supported at all.

**Comment by nikku** [comment]
> https://github.com/camunda/linting/pull/39#issuecomment-1351327251

In this case, let's ship it. Different approaches :+1:

**Review by nikku — APPROVED** [review]

**Pull request merged**
