### PR TITLE
WIP feat: add command line utility

### PR DESCRIPTION
**Pull request by philippfromme**
Makes using the linter from the command line (e.g., `linting test/spec/*.bpmn`) simple.

### CODE REVIEW

**Comment by nikku** [comment]
I'm not sure I understand the use-case for using this library as a CLI tool for linting.

What keeps folks from just using stock bpmnlint + the compat rules?

**Comment by philippfromme** [comment]
> What keeps folks from just using stock bpmnlint + the compat rules?

You can use this without any configuration which is true for both browser and CLI usage.

**Comment by nikku** [comment]
But also it is less pluggable, i.e. does not play nicely with custom lint rules, right?

**Comment by barmac** [comment]
From the command-line utility perspective, the main advantage of @camunda/linting that I can see is the ability to adjust the configuration dynamically based on the target execution version. However, I am not sure if this serves governance well. I imagine that as a diagrams owner, I know where I deploy to, and can set the expected target platform (explicit over implicit). Is there anything I missed?

**Comment by philippfromme** [comment]
Closing this for now.

**Pull request closed without merging**
