### PR TITLE
feat: handle process not executable errors

### PR DESCRIPTION
**Pull request by philippfromme**
* update `bpmnlint-plugin-camunda-compat` to v0.15.0
* handle process not executable errors
* simplify integration tests

image

---

Depends on https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/61
Related to https://github.com/camunda/camunda-modeler/issues/3157

### CODE REVIEW

**Comment by marstamm** [comment]
Is it expected that the `executable` property is not highlighted in Participants?

image

**Comment by philippfromme** [comment]
> Is it expected that the `executable` property is not highlighted in Participants?

Not expected. I will look into this.

**Comment by philippfromme** [comment]
I have created https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/61 which fixes the issue by reporting the error for the participant which is the flow node shown in the properties panel. An alternative approach would have been to account for this in [properties-panel.js](https://github.com/camunda/linting/blob/main/lib/utils/properties-panel.js#L23) but I decided against that. Please have a look. 👀

**Comment by marstamm** [comment]
This fixes it for the case of one Participant, but it leads to other weird behavior on diagrams with multiple Participants:

Recording 2022-11-10 at 15 43 47

the error is only shown on 1 Participant and thus I can fix the error in an participant that does not have an attached error

**Comment by nikku** [comment]
> https://github.com/camunda/linting/pull/36#issuecomment-1310402865

I guess expected is that the error is shown for all participants, right?

**Comment by philippfromme** [comment]
> I guess expected is that the error is shown for all participants, right? Alternatively show the error on the collaboration level; this is actually what I'd expect for collaboration diagrams.
> 
> I'd also not expect a "must be executable" error message in the properties panel. It is not true that one must be executable while the other one does not have to be => I'd not offer any resolution in collaboration diagrams.

Good point. I will have another look.

**Comment by philippfromme** [comment]
I changed https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/61 to report for all affected elements meaning that in a collaboration the error will be shown for each participant. I also changed the error message according to your suggestion, @nikku.
 
brave_XnWzdsqoeT

**Comment by nikku** [comment]
Do we want to change "Must be executable" to "One process must be..."

**Comment by philippfromme** [comment]
Updated it to show a different message for process and collaboration.

### Process

image

### Collaboration

image

@nikku How about that?

**Review by nikku — APPROVED** [review]
Good stuff, works for me!

**Pull request merged**
