### PR TITLE
Support zeebe user task

### PR DESCRIPTION
**Pull request by barmac**
https://github.com/camunda/linting/assets/28307541/c8a74bca-301a-47b1-9709-945a17f6b2d1

* Add human-readable error messages for Zeebe user task errors.
* Add links to properties panel.

----

Related to https://github.com/camunda/product-hub/issues/2126
Related to https://github.com/camunda/camunda-modeler/issues/4087

### CODE REVIEW

**Comment by barmac** [comment]
Requires https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/161

**Review by nikku — COMMENTED** [review]
Two comments:

* We are usually a little bit more descriptive than "Not supported" :arrow_down::

  image

* Default value is Job Worker when creating a new user task, is this desired? Potentially we want to make this dependent on the platform type selected, can we accomplish that? Let's create a follow-up issue to consider a more adaptive "default implementation" selection, i.e. something along the lines of https://github.com/camunda/product-hub/issues/2126#issuecomment-1972967304.

**Comment by barmac** [comment]
> We are usually a little bit more descriptive than "Not supported" ⬇️:

I took this from Zeebe Properties, but can adjust ofc.

**Comment by barmac** [comment]
> Default value is Job Worker when creating a new user task, is this desired? Potentially we want to make this dependent on the platform type selected, can we accomplish that?

It's based on the XML. For all of the legacy tasks, Job Worker is displayed. When we change the implementation to Zeebe user task, a `<zeebe:userTask>` extension is added. This way, we don't forcefeed new feature to the legacy diagrams (no surprises), and also avoid the unnecessary decision requirement ("Implementation must be selected").

We can change the default but it's outside of the scope of linting project, so let's discuss it via https://github.com/camunda/product-hub/issues/2126#issuecomment-1972967304

**Comment by nikku** [comment]
> https://github.com/camunda/linting/pull/101#issuecomment-1973064297

Agreed.

**Comment by barmac** [comment]
> > We are usually a little bit more descriptive than "Not supported" ⬇️:
> 
> I took this from Zeebe Properties, but can adjust ofc.

@nikku How about this?

image

**Comment by barmac** [comment]
Or:

**Comment by nikku** [comment]
Better :arrow_up: (as a general pattern). Not `Form ID` etc. are unsupported, but the _form type_ (or implementation type) chosen. :muscle:

**Comment by barmac** [comment]
The second one right?

**Comment by barmac** [comment]
I pushed https://github.com/camunda/linting/pull/101#issuecomment-1973157619

**Comment by nikku** [comment]
I missed [the first one](https://github.com/camunda/linting/pull/101#issuecomment-1973155463) :see_no_evil: .

To be discussed, but I like it as it is clear (what would _unsupported_ mean if you don't have the error panel open).

**Comment by nikku** [comment]
[Reached out to the group](https://camunda.slack.com/archives/C032H77434N/p1709299980586339). But honestly I think we should just adopt the clear "Supported only in Camunda 8.x and newer" consistently, everywhere.

In this sense I'd be fine to leave the current PR as is (following the existing pattern) and rework the call to action as a follow-up. 

What do you think?

**Comment by barmac** [comment]
I think "Zeebe user task not supported."  guides the user better how to fix the problem. It's not the whole entry, but rather the current value which triggers the error. Perhaps we could make it even better: "Only job worker is supported".

**Comment by nikku** [comment]
> On the other hand, if we want to foster migration, pointing out that migration gives more features, better value, "Supported only in Camunda 8.x" serves that better. So it's a matter of priorities.

I think if we focus a drop down and mark it as an error, then it is clear that the current choice is the issue. So :+1: for (1) focussing the dropdown and marking it as an error and (2) having a descriptive error message that indicates the version compatibility "Supported only in Camunda 8.x".

**Comment by barmac** [comment]
So now it's https://github.com/camunda/linting/pull/101#issuecomment-1973155463 :D

**Comment by nikku** [comment]
Great stuff. Could you create an issue to follow-up on this, consistently applying it across the properties panel? 

There is other places where we currently validate in the wrong place, and I'd imagine the approach you took could work there, too?

image

**Review by nikku — APPROVED** [review]
Please update the attached screen capture :slightly_smiling_face:

**Comment by barmac** [comment]
I created a follow-up issue: https://github.com/camunda/linting/issues/102#issue-2163570580

**Pull request merged**
