### PR TITLE
Adjust timer event definition error messages

### PR DESCRIPTION
**Pull request by barmac**
Related to https://github.com/camunda/camunda-modeler/issues/3084

Requires https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/45 to be merged and integrated.

### CODE REVIEW

**Comment by barmac** [comment]
As shown in the weekly, this does not work correctly yet. I need to add more tests.

**Comment by barmac** [comment]
The tests are present, and we only need to integrate the upstream changes.

**Comment by barmac** [comment]
@nikku @philippfromme Ready for review.

**Review by nikku — APPROVED** [review]
I first stumbled over CRON expressions having 6 components, not five. But that is expected as I've learned in the documentation. Works as documented.

**Pull request merged**
