### PR TITLE
feat: show lint error and warning annotations

### PR DESCRIPTION
**Pull request by philippfromme**
* adds linting annotations for warnings

image

---

Related to https://github.com/camunda/camunda-modeler/issues/3200

### CODE REVIEW

**Comment by barmac** [comment]
Can we improve the contrast of the warnings? It's easy to miss with contrast of 1.67:1. It seems white and yellow don't mix well.

**Comment by philippfromme** [comment]
> Can we improve the contrast of the warnings? It's easy to miss with contrast of 1.67:1. It seems white and yellow don't mix well.

We could get rid of the opacity as a start.

**Comment by philippfromme** [comment]
I removed the opacity. Contrast is slightly better without it:

image

Looking at the web modeler the hover effect wasn't consistent with the other overlays anyway:

brave_j5hIvNDebz

My plan is to look into overlays separately and see whether we can improve them.

@YanaSegal @christian-konrad What do you think?

**Comment by philippfromme** [comment]
My suggestion is to go ahead with this design and tackle those annotations again in the context of improving annotations in the desktop and web modeler.

**Comment by philippfromme** [comment]
@barmac @marstamm Ready to review.

**Comment by philippfromme** [comment]
This only needs a review from the implementation side of things. @marstamm maybe you can have a look.

**Review by marstamm — APPROVED** [review]
Implementation looks good, let's merge 🚀

**Pull request merged**
