### PR TITLE
Bump `bpmnlint-plugin-camunda-compat`

### PR DESCRIPTION
**Pull request by nikku**
Related to https://github.com/camunda/camunda-modeler/issues/3319

### CODE REVIEW

**Comment by nikku** [comment]
Guess we want to add local error messages. I don't know how to do that though.

**Comment by barmac** [comment]
I'll take this over.

**Comment by nikku** [comment]
:rocket:

**Comment by barmac** [comment]
This is how it looks like:

image
image

We should also bump the properties panel for the tests.

**Comment by barmac** [comment]
> We should also bump the properties panel for the tests.
This is done via [`8694ad4`](https://github.com/camunda/linting/pull/40/commits/8694ad4e97c52ec3bbe3f6d96fc517a1feba53df).

**Pull request merged**
